Add rules for Wikiscan.org
EFForg/https-everywhere pull request #19519
Opened 2020-08-24 16:43 UTC by Nintendofan885

Add rules to redirect http://*.wikiscan.org -> https://*.wikiscan.org

2020-08-26 15:43 UTC, pipboy96 requested changes

2020-08-26 15:43 UTC, pipboy96 commented on src/chrome/content/rules/Wikiscan.xml
> +</ruleset>
```suggestion
<ruleset name="Wikiscan">
	<target host="wikiscan.org" />
	<target host="*.wikiscan.org" />

	<rule from="^http:" to="https:" />

	<test url="http://en.wikiscan.org/" />
	<test url="http://frwiktionary.wikiscan.org/" />
	<test url="http://eswikisource.wikiscan.org/" />
</ruleset>
```

2020-08-26 19:38 UTC, Nintendofan885 commented
You don't want to know how angry I am that that was the reason why chrome was failing the check

2020-08-27 06:39 UTC, pipboy96 commented
@Nintendofan885 Actually, it wasn't. This check often fails without any detectable reason. In this case, close and re-open the PR to restart the check.

2020-08-27 06:39 UTC, pipboy96 approved these changes

2020-08-27 09:01 UTC, Nintendofan885 commented
> @Nintendofan885 Actually, it wasn't. This check often fails without any detectable reason. In this case, close and re-open the PR to restart the check.

Oh ok. It just confused me as it suddenly passed the check after I accepted your changes

2020-08-27 09:06 UTC, cschanaj approved these changes

2020-08-27 09:07 UTC, merged

2020-08-27 09:07 UTC, cschanaj commented
thanks!

2020-08-27 09:07 UTC, Nintendofan885 commented
No problem