Update WikiFur.com rules
EFForg/https-everywhere pull request #19556
Opened 2020-09-04 21:15 UTC by Nintendofan885

Update WikiFur.com rules to redirect subdomains that don't start with two letter

List of subdomains (all support https)
wikifur.com
admin.wikifur.com
be.wikifur,com
be-tarask.wikifur.com
board.wikifur.com
by.wikifur.com
da.wikifur.com
de.wikifur.com
en.wikifur.com
eo.wikifur.com
es.wikifur.com
et.wikifur.com
fr.wikifur.com
fursuit.wikifur.com
hu.wikifur.com
it.wikifur.com
ja.wikifur.com
ko.wikifur.com
nb.wikifur.com
no.wikifur.com

2020-09-04 22:00 UTC, pipboy96 requested changes
Please also use tab characters instead of two spaces for indentation.

2020-09-04 22:00 UTC, pipboy96 commented on src/chrome/content/rules/WikiFur.xml
>    <target host="*.wikifur.com" />
Please avoid using wildcards and enumerate subdomains using domain enumeration tools, such as [Amass](https://github.com/OWASP/Amass).

```suggestion
	<target host="www.wikifur.com" />
	<target host="be.wikifur.com" />
	<target host="be-tarask.wikifur.com" />
	<target host="board.wikifur.com" />
	<target host="by.wikifur.com" />
	<target host="cs.wikifur.com" />
	<target host="da.wikifur.com" />
	<target host="de.wikifur.com" />
	<target host="dk.wikifur.com" />
	<target host="dumps.wikifur.com" />
	<target host="en.wikifur.com" />
	<target host="eo.wikifur.com" />
	<target host="es.wikifur.com" />
	<target host="et.wikifur.com" />
	<target host="fr.wikifur.com" />
	<target host="fursuit.wikifur.com" />
	<target host="hu.wikifur.com" />
	<target host="it.wikifur.com" />
	<target host="ja.wikifur.com" />
	<target host="ko.wikifur.com" />
	<target host="nb.wikifur.com" />
	<target host="nl.wikifur.com" />
	<target host="no.wikifur.com" />
	<target host="ny.wikifur.com" />
	<target host="pl.wikifur.com" />
	<target host="pool.wikifur.com" />
	<target host="pt.wikifur.com" />
	<target host="ru.wikifur.com" />
	<target host="stats.wikifur.com" />
	<target host="tl.wikifur.com" />
	<target host="uk.wikifur.com" />
	<target host="zh.wikifur.com" />
```

2020-09-04 22:00 UTC, pipboy96 commented on src/chrome/content/rules/WikiFur.xml
> +  <test url="http://fursuit.wikifur.com/" />
These tests will no longer be needed if you list subdomains individually.

```suggestion
```

2020-09-05 17:38 UTC, pipboy96 approved these changes

2020-09-07 13:33 UTC, cschanaj requested changes
Thank you for your PR. Would you apply the suggestions and use tabs for indentations as per our [contributing guide](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#indentation--misc-stylistic-conventions)?

2020-09-07 13:33 UTC, cschanaj commented on src/chrome/content/rules/WikiFur.xml
>    <target host="wikifur.com" />
```suggestion
	<target host="wikifur.com" />
```

2020-09-07 13:33 UTC, cschanaj commented on src/chrome/content/rules/WikiFur.xml
> +  <rule from="^http:" to="https:" />
```suggestion
	<securecookie host=".+" name=".+"/>
	<rule from="^http:" to="https:" />
```

2020-09-07 13:52 UTC, merged

2020-09-07 13:53 UTC, Nintendofan885 commented
Thank you