WIPO
EFForg/https-everywhere pull request #19606
Opened 2020-09-22 05:06 UTC by MilanKral

2020-09-22 09:46 UTC, pipboy96 requested changes

2020-09-22 09:46 UTC, pipboy96 commented on src/chrome/content/rules/WIPO.int.xml
> +<ruleset name="WIPO.int">
```suggestion
<!--
	Mismatched:
		- wipo.int
-->
<ruleset name="WIPO.int (partial)">
```

2020-09-27 19:47 UTC, MilanKral commented on src/chrome/content/rules/WIPO.int.xml
> +<ruleset name="WIPO.int">
ok

2020-10-05 20:12 UTC, zoracon approved these changes

2020-10-05 20:12 UTC, merged