Create Whoer.net.xml for issue #18059
EFForg/https-everywhere pull request #19609
Opened 2020-09-25 21:23 UTC by bfosterscripps

### Related PRs

- https://github.com/EFForg/https-everywhere/pull/18713
- https://github.com/EFForg/https-everywhere/pull/19550
- https://github.com/EFForg/https-everywhere/pull/19551

### Related Issues

- https://github.com/EFForg/https-everywhere/issues/18059

2020-10-05 13:59 UTC, bfosterscripps commented
I believe this is ready for review @pipboy96

2020-10-05 15:21 UTC, pipboy96 requested changes

2020-10-05 15:21 UTC, pipboy96 commented on src/chrome/content/rules/Surfshark.com.xml
> +	t: timeout on https
```suggestion
	r: connection refused
	t: timeout on https
```

2020-10-05 15:21 UTC, pipboy96 commented on src/chrome/content/rules/Surfshark.com.xml
> +
```suggestion
```

2020-10-05 15:21 UTC, pipboy96 commented on src/chrome/content/rules/Whoer.net.xml
> +
```suggestion
```

2020-10-05 15:21 UTC, pipboy96 commented on src/chrome/content/rules/Whoer.net.xml
> +	t: timeout on https
```suggestion
	r: connection refused
```

2020-10-15 22:16 UTC, zoracon approved these changes

2020-10-15 22:17 UTC, merged