Add Nic.bc.ca.xml
EFForg/https-everywhere pull request #19643
Opened 2020-10-03 10:39 UTC by fuglede

Closes #19451.

2020-10-03 12:57 UTC, pipboy96 requested changes

2020-10-03 12:57 UTC, pipboy96 commented on src/chrome/content/rules/Nic.bc.ca.xml
> +	<rule from="^http://(?:www\.)?nic\.bc.ca/"
```suggestion
	<rule from="^http://(?:www\.)?nic\.bc\.ca/"
```

2020-10-03 12:59 UTC, fuglede commented on src/chrome/content/rules/Nic.bc.ca.xml
> +	<rule from="^http://(?:www\.)?nic\.bc.ca/"
Whoops, fixed!

2020-10-03 13:21 UTC, pipboy96 requested changes

2020-10-03 13:21 UTC, pipboy96 commented on src/chrome/content/rules/Nic.bc.ca.xml
> +		to="https://www.nic.bc.ca/" />
```suggestion
	<rule from="^http://nic\.bc\.ca/" to="https://www.nic.bc.ca/" />

	<rule from="^http:" to="https:" />
```

2020-10-04 11:38 UTC, pipboy96 approved these changes

2020-10-21 23:42 UTC, zoracon approved these changes

2020-10-21 23:42 UTC, merged