Add Scssoft.com.xml
EFForg/https-everywhere pull request #19666
Opened 2020-10-12 16:49 UTC by netravnen

2020-10-13 00:31 UTC, pipboy96 requested changes

2020-10-13 00:31 UTC, pipboy96 commented on src/chrome/content/rules/Scssoft.com.xml
> +	<target host="blog.scssoft.com" />
```suggestion
	<target host="scssoft.com" />
	<target host="www.scssoft.com" />
	<target host="blog.scssoft.com" />
	<target host="chat.scssoft.com" />
	<target host="eshop.scssoft.com" />
	<target host="forum.scssoft.com" />
	<target host="ks.scssoft.com" />
	<target host="mail.scssoft.com" />
	<target host="modding.scssoft.com" />
	<target host="qa.scssoft.com" />
	<target host="sendy.scssoft.com" />
```

2020-10-13 00:31 UTC, pipboy96 commented on src/chrome/content/rules/Scssoft.com.xml
> +-->
This comment is redundant.

```suggestion
```

2020-10-19 18:55 UTC, netravnen commented on src/chrome/content/rules/Scssoft.com.xml
> +	<target host="blog.scssoft.com" />
🆗

2020-10-19 18:55 UTC, netravnen commented on src/chrome/content/rules/Scssoft.com.xml
> +-->
🆗

2020-11-02 00:34 UTC, J0WI commented on src/chrome/content/rules/Scssoft.com.xml
> +<ruleset name="scssoft.com">
Cloud you also add [comments for non-working subdomains](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#non-working-hosts)?
```
huntingunlimited.scssoft.com
karolina.scssoft.com
www2.scssoft.com
```

2021-06-24 19:36 UTC, closed without merging