Create Blogto.com.xml
EFForg/https-everywhere pull request #19691
Opened 2020-10-17 03:14 UTC by csavard-sudo

2020-10-21 23:38 UTC, zoracon requested changes
Looks good! Could use a few other subdomains.

Please add 
`media.blogto.com`
`contests.blogto.com`

2020-10-22 08:34 UTC, Nintendofan885 commented
> Looks good! Could use a few other subdomains.
> 
> Please add
> `media.blogto.com`
> `contests.blogto.com`

contests.blogto.com seems to give a 'host not resolved error'

2020-10-22 15:58 UTC, zoracon commented
> > Looks good! Could use a few other subdomains.
> > Please add
> > `media.blogto.com`
> > `contests.blogto.com`
> 
> contests.blogto.com seems to give a 'host not resolved' error

I am seeing that as well, you can remove that

2020-11-02 01:00 UTC, J0WI commented on src/chrome/content/rules/Blogto.com.xml
> +	<target host="media.blogto.com" />
I also found `api.blogto.com` and `patios.blogto.com`

2020-11-22 23:24 UTC, csavard-sudo reviewed
done :)

2020-11-22 23:38 UTC, J0WI approved these changes

2020-12-04 23:13 UTC, merged