Update OpenVPN.xml
EFForg/https-everywhere pull request #19732
Opened 2020-10-28 16:23 UTC by TotalCaesar659

https://github.com/EFForg/https-everywhere/issues/15750

2020-10-30 16:34 UTC, J0WI commented on src/chrome/content/rules/OpenVPN.xml
> +	<rule from="^http://www\.openvpn\.net/" to="https://openvpn.net/" />
https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#snapping-redirects

2020-10-30 18:35 UTC, pipboy96 requested changes

2020-10-30 18:35 UTC, pipboy96 commented on src/chrome/content/rules/OpenVPN.xml
> +	<rule from="^http://www\.openvpn\.net/" to="https://openvpn.net/" />
This redirect is not necessary.

```suggestion
```

2020-11-02 13:55 UTC, J0WI approved these changes

2020-11-02 13:56 UTC, merged