Add TikTok.com.xml
EFForg/https-everywhere pull request #19763
Opened 2020-11-03 15:10 UTC by J0WI

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring existing code
- [x] New Ruleset
- [ ] Existing Ruleset

## For Rulesets: Testing

- [ ] Travis CI completed without errors (triggered upon pull request)

2020-11-03 23:18 UTC, pipboy96 requested changes

2020-11-03 23:18 UTC, pipboy96 commented on src/chrome/content/rules/TikTok.com.xml
> +	<rule from="^http://tiktok\.com/" to="https://www\.tiktok\.com/" />
```suggestion
	<rule from="^http://tiktok\.com/" to="https://www.tiktok.com/" />
```

2020-11-07 20:09 UTC, Bisaloo commented on src/chrome/content/rules/TikTok.com.xml
> +	<target host="*.tiktokcdn.com" />
It might be good to add a "real" test URL, with some content. What do you think?

2020-11-07 20:12 UTC, Bisaloo commented
Nevermind, you can disregard my comments relating to the main domain since it's apparently preloaded

2020-11-16 05:07 UTC, zoracon approved these changes

2020-11-16 05:07 UTC, merged