Add rules for schwarz-fritz.de
EFForg/https-everywhere pull request #19799
Opened 2020-11-21 07:56 UTC by fabianschwarzfritz

Fixes #(issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring existing code
- [x] New Ruleset
- [ ] Existing Ruleset

## For Rulesets: Testing

- [ ] Travis CI completed without errors (triggered upon pull request)

## Existing Contributors
If you have open PRs that have not been closed or merged, please revisit them by searching: `https://github.com/EFForg/https-everywhere/issues?q=is%3Aopen+assignee%3A[yourusernamehere]`.

2020-11-26 08:03 UTC, fabianschwarzfritz commented
I see the jenkins build requires a `<test>` section. I will add one!

2020-12-22 19:26 UTC, zoracon commented
@fabianschwarzfritz Here is a test example for your reference
https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#example-ruleset-after-style-guidelines-are-applied-with-test-urls

2020-12-28 20:11 UTC, pipboy96 commented
@fabianschwarzfritz Your website no longer has a valid certificate (neither on www.schwarz-fritz.de nor on schwarz-fritz.de). Also, it's recommended for the website owners to use [HSTS preloading](https://hstspreload.org/) instead of adding rulesets for their websites to HTTPS Everywhere since the preloaded websites get redirected to HTTPS without extensions on both Chrome and Firefox.

2020-12-28 20:13 UTC, pipboy96 requested changes
Please fix the certificate issue and do not use wildcard targets. Otherwise it's fine, although it's recommended that you use HSTS preloading instead.

2020-12-28 20:13 UTC, pipboy96 commented on src/chrome/content/rules/schwarz-fritz.de.xml
> +</ruleset>
```suggestion
<ruleset name="schwarz-fritz.de">
	<target host="schwarz-fritz.de" />
	<target host="www.schwarz-fritz.de" />

	<rule from="^http:" to="https:" />
</ruleset>
```

2021-06-24 19:37 UTC, closed without merging