Create bitlaunch.io.xml
EFForg/https-everywhere pull request #19884
Opened 2021-01-03 18:31 UTC by BitLaunchIO

Fixes #(issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring existing code
- [x] New Ruleset
- [ ] Existing Ruleset

2021-01-04 05:55 UTC, pipboy96 commented
@BitLaunchIO Thanks for contribution! Since you are the website owner, it's recommended that you use HSTS preloading instead. It's more effective since it doesn't require the user to have HTTPS Everywhere installed, as long as they are on a modern version of Chrome or Firefox.

2021-01-04 06:00 UTC, pipboy96 requested changes

2021-01-04 06:00 UTC, pipboy96 commented on src/chrome/content/rules/bitlaunch.io.xml
> +	<target host="pay.bitlaunch.io" />
```suggestion
	<target host="bitlaunch.io" />
	<target host="www.bitlaunch.io" />
	<target host="affiliates.bitlaunch.io" />
	<target host="analytics.bitlaunch.io" />
	<target host="app.bitlaunch.io" />
	<target host="blacklist.bitlaunch.io" />
	<target host="developers.bitlaunch.io" />
	<target host="pay.bitlaunch.io" />
```

2021-01-04 13:19 UTC, BitLaunchIO commented
@pipboy96 Thank you.

We are observing an SSL stripping MITM attack on our payment endpoint via malicious Tor exit relays, in which the cryptocurrency payment address is replaced with that of the attacker. HSTS is now enabled. We'd still greatly appreciate consideration for merging so that all eventualities are covered.

2021-01-05 00:07 UTC, pipboy96 commented
@BitLaunchIO Also, an unrelated question: which datacenter are BitLaunch VPSes located in?

2021-01-05 03:37 UTC, pipboy96 approved these changes
LGTM

2021-01-05 16:14 UTC, merged