Update Turner.com.xml
EFForg/https-everywhere pull request #19925
Opened 2021-02-13 16:38 UTC by TotalCaesar659

## Type of change

- [x] Existing Ruleset

2021-03-04 00:06 UTC, zoracon requested changes
Errors in test coverage:
```
ERROR src/chrome/content/rules/Turner.com.xml: Duplicated test URL found http://press.turner.com/

ERROR src/chrome/content/rules/Turner.com.xml: Duplicated test URL found http://submission.turner.com/

ERROR src/chrome/content/rules/Turner.com.xml: Duplicated test URL found http://research.turner.com/

ERROR src/chrome/content/rules/Turner.com.xml: Duplicated test URL found http://pressroom.turner.com/

ERROR src/chrome/content/rules/Turner.com.xml: Duplicated test URL found http://sts.turner.com/

ERROR src/chrome/content/rules/Turner.com.xml: Duplicated test URL found http://prensa.turner.com/

ERROR src/chrome/content/rules/Turner.com.xml: Duplicated test URL found http://recruiting.turner.com/

ERROR src/chrome/content/rules/Turner.com.xml: Duplicated test URL found http://news.turner.com/
```

2021-03-04 14:13 UTC, TotalCaesar659 commented
Hm, strange, I can't find other ruleset with them.

2021-04-14 09:00 UTC, cschanaj commented on src/chrome/content/rules/Turner.com.xml
> +	<target host="prensa.turner.com" />
`prensa.turner.com` appeared multiple times in this ruleset, please remove the duplicates within the same file. thanks.

2021-09-15 18:44 UTC, zoracon requested changes
Errors with the following domains need attention:
```
ERROR src/chrome/content/rules/Turner.com.xml: Fetch error: http://turner.com/ => https://turner.com/: (7, 'Failed to connect to turner.com port 443: Connection timed out')

ERROR src/chrome/content/rules/Turner.com.xml: Fetch error: http://ttv-content-asperatx.awsbest.turner.com/ => https://ttv-content-asperatx.awsbest.turner.com/: (60, 'SSL certificate problem: certificate has expired')

ERROR src/chrome/content/rules/Turner.com.xml: Fetch error: http://ttv-content-asperatx-all.awsbest.turner.com/ => https://ttv-content-asperatx-all.awsbest.turner.com/: (60, 'SSL certificate problem: certificate has expired')

ERROR src/chrome/content/rules/Turner.com.xml: Fetch error: http://ttv-content-dev-asperatx.dev.awsbest.turner.com/ => https://ttv-content-dev-asperatx.dev.awsbest.turner.com/: (60, 'SSL certificate problem: certificate has expired')

ERROR src/chrome/content/rules/Turner.com.xml: Fetch error: http://ttv-content-dev-asperatx-all.dev.awsbest.turner.com/ => https://ttv-content-dev-asperatx-all.dev.awsbest.turner.com/: (60, 'SSL certificate problem: certificate has expired')

ERROR src/chrome/content/rules/Turner.com.xml: Fetch error: http://zeus.cp-ext.turner.com/ => https://zeus.cp-ext.turner.com/: (6, 'Could not resolve host: zeus.cp-ext.turner.com')

ERROR src/chrome/content/rules/Turner.com.xml: Fetch error: http://help.turner.com/ => https://help.turner.com/: (60, 'SSL certificate problem: certificate has expired')
```

2022-02-01 17:59 UTC, closed without merging